### ISSUE TITLE
The example in this repo is different from your final thesis

### ISSUE THREAD

**Issue by ydawei** [pettni/um-thesis#1]
Hi,

Thanks for the effort of making such a nice template! Meanwhile, I notice that the generated example in this repo is somehow different from your final thesis, such as link colors, margins. Would it be possible to guide me how to tweak it to match the final version?

Thanks again.

**Comment by pettni** [comment]
Thanks for pointing out the issue with the margins, I wasn't aware that it was different and still not sure what the reason was. In general the template contains several (what I consider) improvements over my thesis, but margins was not one of the things I had intended to change.

I updated the template a little and the margins are now closer to how I had them. They can be modified by changing the DIV variable on line 13 in ```layout/preamble.tex```. See the koma manual for more info

http://ctan.math.washington.edu/tex-archive/macros/latex/contrib/koma-script/doc/scrguien.pdf#chapter.2

Regarding link coloring I prefer how it looks in the template so I will keep it that way, but it is easy to modify on line 77-81 in ```preamble.tex```.  I believe my thesis used the defaults that you get without passing any arguments when loading ```hyperref```. See the ```hyperref``` package for more info.

http://mirror.las.iastate.edu/tex-archive/macros/latex/contrib/hyperref/doc/manual.pdf#subsection.3.5
